name: "Manage Active Issues, PRs & Merged Branches"

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 1:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  active:
    runs-on: ubuntu-latest
    steps:
      - name: Mark Active Issues and PRs
        uses: actions/stale@v9
        with:
          stale-issue-message: "This issue remains active as there has been recent activity."
          stale-pr-message: "This PR remains active as there has been recent activity."
          days-before-stale: 180
          days-before-close: 30
          exempt-issue-labels: "keep"
          exempt-pr-labels: "keep"

  cleanup-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate branch checks

      - name: Fetch All Branches
        run: git fetch --all --prune

      - name: List Active Branches With Recent Activity in Last 2 Days
        run: |
          echo "branch_name,last_commit_date,committed_in_branch" > active_branches.csv
          for branch in $(git for-each-ref --format '%(refname:short) %(committerdate:unix)' refs/remotes/origin | awk -v date=$(date -d '2 days ago' +%s) '$2 >= date {print $1}'); do
            if [[ "$branch" != "origin/main" && "$branch" != "origin/dev" ]]; then
              branch_name=${branch#origin/}
              last_commit_date=$(git log -1 --format=%ci "$branch")
              committed_in_branch=$(git branch -r --contains "$branch" | grep -Eo "origin/(main|dev)" | head -n 1 | cut -d '/' -f2 || echo "N/A")
              echo "$branch_name,$last_commit_date,$committed_in_branch" >> active_branches.csv
            fi
          done

      - name: List PR Approved and Merged Active Branches in Last 2 Days
        run: |
          echo "Checking branches with PRs approved and merged into main or dev in the last 2 days..."
          for branch in $(gh api repos/${{ github.repository }}/pulls --jq '.[] | select(.merged_at != null and (.base.ref == "main" or .base.ref == "dev")) | select(.merged_at | fromdateiso8601 >= (now - 172800)) | .head.ref'); do
            last_commit_date=$(git log -1 --format=%ci "origin/$branch" || echo "N/A")
            committed_in_branch=$(gh api repos/${{ github.repository }}/pulls --jq ".[] | select(.head.ref == \"$branch\") | .base.ref" || echo "N/A")
            echo "$branch,$last_commit_date,$committed_in_branch" >> active_branches.csv
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV File
        uses: actions/upload-artifact@v4
        with:
          name: active-branches-report
          path: active_branches.csv
