name: "Manage Inactive Issues, PRs & Unmerged Branches"

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 1:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  inactive-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate branch checks

      - name: Fetch All Branches
        run: git fetch --all --prune

      - name: Identify Inactive Branches (More than 5 Days)
        run: |
          echo "Branch,Last Commit Date" > inactive-branches-report.csv
          
          echo "Checking branches that have not had commits in the last 5 days..."
          for branch in $(git for-each-ref --format '%(refname:short) %(committerdate:unix)' refs/remotes/origin | awk -v date=$(date -d '5 days ago' +%s) '$2 < date {print $1}'); do
            if [[ "$branch" != "origin/main" && "$branch" != "origin/dev" ]]; then
              branch_name=${branch#origin/}
              last_commit_date=$(git log -1 --format=%ci "$branch")
              echo "$branch_name,$last_commit_date" >> inactive-branches-report.csv
            fi
          done

      - name: Identify PR Branches with No Activity in More Than 5 Days
        run: |
          echo "Checking PR branches with no updates in more than 5 days..."
          for branch in $(gh api repos/${{ github.repository }}/pulls --jq '.[] | select(.updated_at | fromdateiso8601 < (now - 432000)) | .head.ref'); do
            last_commit_date=$(git log -1 --format=%ci origin/$branch || echo "Unknown")
            echo "$branch,$last_commit_date" >> inactive-branches-report.csv
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Inactive Branch Report
        uses: actions/upload-artifact@v4
        with:
          name: inactive-branches-report
          path: inactive-branches-report.csv
          retention-days: 30
